### ISSUE TITLE
driveshare-gui 0.4.2 not working on OS X

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#116]
Installation of the OS X binary works but i can't start it. I get the following exception:

Uncaught Exception:
Error: Cannot find module 'electron-safe-ipc/host'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.<anonymous> (/Users/skunk/Documents/driveshare-gui/build/main.js:13:13)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

Same problem if i run "npm start".

**Comment by gordonwritescode** [comment]
You are missing a dependency, try:

```
rm -r node_modules app/node_modules
npm install
```

**Comment by JeremyPepper2** [comment]
I have the same problem.

**Comment by gordonwritescode** [comment]
@littleskunk when you built the release for OSX, I am guessing that a `npm install` was missed.

**Comment by littleskunk** [comment]
I reinstalled nodejs and build a new binary. This time the binary is fine. I don't know what the problem was but it should work now. I replaced the broken binary. Download it and try again.

**Comment by littleskunk** [comment]
Found the reason for the currupted binary. The curl upload is not working.
