### ISSUE TITLE
Drive share GUI 0.5.0 "Uncaught Exception: SyntaxError: Unexpected token" on Linux Mint 17.3 after 13.01.2015 upgrade.

### ISSUE THREAD

**Issue by bricemw** [Storj/driveshare-gui#170]
Hi devs, love your work, keep going! :)
Sadly after Linux mint 17.3 updated tonight, I cannot start drive-share-gui 0.5 again, not even 0.4.3 after remove, etc...

Uncaught Exception:
SyntaxError: Unexpected token ,
    at Object.parse (native)
    at UserData._read (/opt/driveshare/resources/app.asar/lib/userdata.js:48:21)
    at new UserData (/opt/driveshare/resources/app.asar/lib/userdata.js:28:23)
    at EventEmitter.<anonymous> (/opt/driveshare/resources/app.asar/main.js:42:26)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

This is the update log of Linux mint:
![capture du 2016-01-13 23 06 42](https://cloud.githubusercontent.com/assets/5060488/12309362/84708332-ba4a-11e5-9f36-a1aa9e6af3a7.png)

I can only start driveshare-gui from root user, but i don't like it to be that way...

Best wishes for this new year.

Brice MW (bmw or med4u on slack)

**Comment by littleskunk** [comment]
https://github.com/Storj/driveshare-gui/issues/164

Please delete the driveshare settings.json. Should be somewhere in your home directory.

**Comment by bricemw** [comment]
I have remove the settings.json that I have found in /home/me/.storj , removed 0.5 and reboot. After reboot, reinstall : exactly the same error..

Uncaught Exception:
SyntaxError: Unexpected token ,
    at Object.parse (native)
    at UserData._read (/opt/driveshare/resources/app.asar/lib/userdata.js:48:21)
    at new UserData (/opt/driveshare/resources/app.asar/lib/userdata.js:28:23)
    at EventEmitter.<anonymous> (/opt/driveshare/resources/app.asar/main.js:42:26)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

**Comment by littleskunk** [comment]
That was the dataserv-cleint settings.json.

**Comment by bricemw** [comment]
Ok, "oups"! :) Hopefully I had a backup.
But I do not found the driveshare config.json ...

**Comment by gordonwritescode** [comment]
Hey d00d. Should be in `~/.config/driveshare`!

**Comment by bricemw** [comment]
Oh it works again with deleting the config.json file! :+1:  

Yeah I’m kind of a linux n00b not knowing where all config files are ;)

It's weird that I had this issue after a system update...
Thank you both for your help!
