### ISSUE TITLE
Height Calculated Incorrectly 

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#35]
Error log:
```
dataserv-client version 2.1.4

C:\Users\super3\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=C:\Users\super3\Desktop\test --max_size=2 farm
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/address
```

I specified 2 GB, but max height was set to 2. 2G should be passed to max size instead.

**Comment by littleskunk** [comment]
GUI store size = 1.35 TB will end up with following error.

"View logs" says: C:\Users\xandry\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=D:\sjcx --max_size=1.35 farm 
Traceback (most recent call last): 
 File "dataserv-client", line 10, in <module> 
 File "E:\dataserv-client\dataserv_client\cli.py", line 188, in main 
 File "E:\dataserv-client\dataserv_client\api.py", line 46, in __init__ 
 File "E:\dataserv-client\dataserv_client\deserialize.py", line 67, in byte_count 
 File "E:\dataserv-client\dataserv_client\deserialize.py", line 9, in positive_nonzero_integer 
 File "C:\Python34\lib\site-packages\btctxstore\deserialize.py", line 81, in positive_integer 
ValueError: invalid literal for int() with base 10: '1.35'

**Comment by gamedevsam** [comment]
This is what happens when you make a release at 1am in the morning. Sorry about that, a bug fix release has been made.

**Comment by super3** [comment]
Works great for me now.
