### ISSUE TITLE
DriveShare Thinks .NET is Not Installed

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#44]
[Project:SM]

Downloads then I get this error:

```There was an issue running dataserv-client, make sure you have Microsoft .NET Framework installed and try again. If the issue persists let us know on github.```

When I try to install .NET:

```Details

.NET Framework 4.6 or a later update is already installed on this computer.
```

It was running just fine before until I restarted it.

**Comment by super3** [comment]
Looks like it is running the newest version of dataserv-client, which might cause issues:

```
Obtaining download URL for dataserv-client
Downloading https://github.com/Storj/dataserv-client/releases/download/v2.1.4/dataserv-client-2.1.4.win32.zip
Download complete, extracting C:\Users\work\AppData\Roaming\DriveShare/tmp/dataserv-client.zip
Extraction complete, validating dataserv-client
Error: Command failed: C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe version
Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 188, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 68, in __init__
  File "E:\dataserv-client\dataserv_client\control\config.py", line 60, in get
  File "E:\dataserv-client\dataserv_client\control\config.py", line 103, in migrate
KeyError: '2.1.11'

C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=D:\ --max_size=1.8TB farm
Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 188, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 68, in __init__
  File "E:\dataserv-client\dataserv_client\control\config.py", line 60, in get
  File "E:\dataserv-client\dataserv_client\control\config.py", line 103, in migrate
KeyError: '2.1.11'
```

**Comment by yoda1204** [comment]
I was having the same issue here. In looking into this issue I found that the driveshare-gui could not file a file. The file that looks like it was missing is the "msvcr100.dll". If you install the "http://www.microsoft.com/en-us/download/details.aspx?id=26999" [Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update] on windows 10 this fixes the problem for me.
Thanks
Yoda1204

**Comment by super3** [comment]
I don't actually think this is the error. Looks like driveshare-gui is pulling an old version of dataserv-client.

**Comment by super3** [comment]
Created a new issue #46
