### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#47]
When running 2.1.4 I get this strange error:

```
C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=D:\ --max_size=1.8GB farm
Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 188, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 68, in __init__
  File "E:\dataserv-client\dataserv_client\control\config.py", line 60, in get
  File "E:\dataserv-client\dataserv_client\control\config.py", line 103, in migrate
KeyError: '2.1.11'
```

**Comment by littleskunk** [comment]
You did run dataserv-client version 2.1.11 once. It migrates your config.json file from 2.1.4 to 2.1.11. To run version 2.1.4 you have to delete or downgrade the config file. To downgrade open the config file (%userprifle%\.storj\config.json) and change the version number.

**Comment by super3** [comment]
Ah ok. Looks all fixed now.
